### ISSUE TITLE
RuntimeException occurred / EACCES (Permission denied) when trying to save a photo/gif/video on android < 13

### ISSUE THREAD

**Issue by mfschieber** [capacitor-community/media#77]
**Describe the bug**
i have an error when trying to download a photo/video/gif on android 10/12 : 
![Screenshot 2023-12-05 at 18 04 20](https://github.com/capacitor-community/media/assets/102966580/bdd79ed4-384c-41a0-9f06-7f094fa9a131)

Here is the error i got on android studio : 
<img width="1488" alt="Screenshot 2023-12-05 at 18 03 58" src="https://github.com/capacitor-community/media/assets/102966580/f21d2ec3-e4de-4291-aaef-456220b1e5f3">

the request fails and this error is displayed even if the file has been downloaded. 

**To Reproduce**
Download a gif through saveGif , a photo through savePhoto or a video through saveVideo on android 10/12

**Expected behavior**
We expect the request to be successful. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: android 10/12
 - Version 5.3.0

**Additional context**
This issue is probably due to the update in permissions from android. Adding android:requestLegacyExternalStorage="true"
 in manifest solves the issue, but we can't do that as it is prohibited by android for applications targeting level 33 of the API. 
It has already been raised here : https://github.com/capacitor-community/media/issues/71
But issue has not really been resolved, the code has just been put inside a try/catch. 
From what i saw, we're downloading the file in Download folder, then we copy it in the albumIdentifier, and then we're trying to delete the file in Download folder, but it fails. Maybe we're missing a request for the permissions of the download file before deleting a file there ?

**Comment by jarabito11** [comment]
I have the same problem. I need help please.

**Comment by nkalupahana** [comment]
Should be fixed on 5.3.1, please confirm.

**Comment by mfschieber** [comment]
Hey @nkalupahana , thank you for helping on this issue 🙏 

I tested latest version on my android 10, and i still have the issue RuntimeException occurred, and now the photo is not downloaded anymore. 
Here is the issue i have on the plugin side : 
<img width="1684" alt="Screenshot 2023-12-06 at 10 05 47" src="https://github.com/capacitor-community/media/assets/102966580/d6697658-ec89-47d8-9079-d9bc8ed4ae03">

When storage permission was required, i accepted it, but i still have this permission denial after that. I'm trying to save my picture on an existing 'YOOBIC' folder. 

Issue is not reproducible on android 13.

**Comment by jarabito11** [comment]
@nkalupahana This is my code:

```
 let params;
    if(this.platform.is('ios')){
      params = {
        path: fileUrl
      };
    }else{
      let album = await this.getAlbumIdentifier();
      console.log(album);
      
      if (!album.success){
        this.tools.showToast('No se ha encontrado ningún album en el dispositivo.');
        return;
      }

      params = {
        path: fileUrl,
        albumIdentifier: album.identifier
      };
    }

    Media.saveVideo(params).then((res) => {
      this.tools.showToast('Vídeo descargado.');
    }).catch((err) => {
      console.error(err);
      this.tools.showToast('Ha ocurrido un error al descargar el vídeo.');
    }).finally(() => {
      loader.dismiss();
    });
```


but I have this error:

![Captura de pantalla 2023-12-06 a las 10 32 38](https://github.com/capacitor-community/media/assets/33698838/9a0f232c-3950-4eb9-af03-7c78fd86193e)

@mfschieber is the same problem

**Comment by nkalupahana** [comment]
Can you both try the example app in the `example` folder? This is what I use to debug issues, and it currently works for me on the Android 10 emulator. This will help me narrow down the issue.

**Comment by mfschieber** [comment]
Hey @nkalupahana, I tested the example app and didn't have the issue. I found the issue. What i was doing:  I search for my YOOBIC album in the getAlbums, to get the identifier. If i don't find it, I create a new YOOBIC album. The path of my YOOBIC album was this one :  _"/storage/emulated/0/Pictures/YOOBIC"_ ➝ As i don't have access to pictures with the new API we're targeting (33), i'm getting a permission denial for wanting to save my picture inside this YOOBIC folder.
Deleting my folder and re-creating it from the createAlbum function worked fine on android 10 & 13. Now my album is inside _Android/media._ 
Do you think it's possible to add on your side a property on the album objects to know if we can write inside those folders or no ? for now we just found a workaround to rename this folder to a new name to use the createAlbum for everyone.

**Comment by nkalupahana** [comment]
Here's what I think I can do -- I'll implement #74, so that way you have a `getAlbumPath()` function that tells you where your app's albums are. That way, instead of just checking albums by name, you can check them by name and the start of the album path. If there isn't one there (e.g. they updated their phone and now they have a different album path because of android version), you'll know to re-create the album.

**Comment by mfschieber** [comment]
thanks @nkalupahana , would be nice ! i'm suscribing to this feature to test that when it's ready 👍

**Comment by amakh** [comment]
> Hey @nkalupahana, I tested the example app and didn't have the issue. I found the issue. What i was doing: I search for my YOOBIC album in the getAlbums, to get the identifier. If i don't find it, I create a new YOOBIC album. The path of my YOOBIC album was this one :  _"/storage/emulated/0/Pictures/YOOBIC"_ ➝ As i don't have access to pictures with the new API we're targeting (33), i'm getting a permission denial for wanting to save my picture inside this YOOBIC folder. Deleting my folder and re-creating it from the createAlbum function worked fine on android 10 & 13. Now my album is inside _Android/media._ Do you think it's possible to add on your side a property on the album objects to know if we can write inside those folders or no ? for now we just found a workaround to rename this folder to a new name to use the createAlbum for everyone.

I'm curious, did you ask your users to rename the folder themselves? And even if you rename the folder, half of the medias are stored in this old folder and the rest will be stored in the new one. Or maybe did you find a workaround to merge / transfer the albums?

**Comment by mfschieber** [comment]
> > Hey @nkalupahana, I tested the example app and didn't have the issue. I found the issue. What i was doing: I search for my YOOBIC album in the getAlbums, to get the identifier. If i don't find it, I create a new YOOBIC album. The path of my YOOBIC album was this one :  _"/storage/emulated/0/Pictures/YOOBIC"_ ➝ As i don't have access to pictures with the new API we're targeting (33), i'm getting a permission denial for wanting to save my picture inside this YOOBIC folder. Deleting my folder and re-creating it from the createAlbum function worked fine on android 10 & 13. Now my album is inside _Android/media._ Do you think it's possible to add on your side a property on the album objects to know if we can write inside those folders or no ? for now we just found a workaround to rename this folder to a new name to use the createAlbum for everyone.
> 
> I'm curious, did you ask your users to rename the folder themselves? And even if you rename the folder, half of the medias are stored in this old folder and the rest will be stored in the new one. Or maybe did you find a workaround to merge / transfer the albums?

Hey @amakh , we're waiting for the gelAlbumsPath() to have access to the folders where we can actually write into. At the same time we just renamed the name of the album where we will store our medias, so that it will create a new album for all the users of the app in a storage folder where we can write into.

**Comment by amakh** [comment]
> > > Hey @nkalupahana, I tested the example app and didn't have the issue. I found the issue. What i was doing: I search for my YOOBIC album in the getAlbums, to get the identifier. If i don't find it, I create a new YOOBIC album. The path of my YOOBIC album was this one :  _"/storage/emulated/0/Pictures/YOOBIC"_ ➝ As i don't have access to pictures with the new API we're targeting (33), i'm getting a permission denial for wanting to save my picture inside this YOOBIC folder. Deleting my folder and re-creating it from the createAlbum function worked fine on android 10 & 13. Now my album is inside _Android/media._ Do you think it's possible to add on your side a property on the album objects to know if we can write inside those folders or no ? for now we just found a workaround to rename this folder to a new name to use the createAlbum for everyone.
> > 
> > 
> > I'm curious, did you ask your users to rename the folder themselves? And even if you rename the folder, half of the medias are stored in this old folder and the rest will be stored in the new one. Or maybe did you find a workaround to merge / transfer the albums?
> 
> Hey @amakh , we're waiting for the gelAlbumsPath() to have access to the folders where we can actually write into. At the same time we just renamed the name of the album where we will store our medias, so that it will create a new album for all the users of the app in a storage folder where we can write into.

Ok I see, thank you. Some of our users were asking why they couldn't find medias in the old album (they didn't check other paths or they were pointing the initial folder to be sync by other tools).
I guess we will just continue to answer to them telling to use the new album now.

**Comment by nkalupahana** [comment]
`getAlbumsPath()` has been added in 5.4.0, and the example code has been updated to use it. If you need any help with this, please open a new issue!
